// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5KHSJPhfb-lEx5QNUjYMYbc0mkpilms',
    appId: '1:295854641269:web:ed0f8f9a2cf158a24fe83c',
    messagingSenderId: '295854641269',
    projectId: 'stadium-project',
    authDomain: 'stadium-project.firebaseapp.com',
    storageBucket: 'stadium-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIi-sdeNFs2hJIZU1ZVDdxO3NZioVELpI',
    appId: '1:295854641269:android:17e61ea57f69044f4fe83c',
    messagingSenderId: '295854641269',
    projectId: 'stadium-project',
    storageBucket: 'stadium-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gow8xHOOzjFMvj308A_WxN8NG5JP2HM',
    appId: '1:295854641269:ios:975cff9415037f264fe83c',
    messagingSenderId: '295854641269',
    projectId: 'stadium-project',
    storageBucket: 'stadium-project.appspot.com',
    iosClientId: '295854641269-o2eo1djh7dihn9rra81j78gi0mtiu7p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stadiumApp',
  );
}
